apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "359722584366.dkr.ecr.us-east-1.amazonaws.com/backend:31605b04caa739874baa989699793efd077ac765"
          ports:
            - containerPort: 8080
              name: backend
