apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "359722584366.dkr.ecr.us-east-1.amazonaws.com/frontend:d986f4c013f0880fedfdf9702a0d858b459a5d5b"
          ports:
            - containerPort: 80
              name: frontend
