apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "359722584366.dkr.ecr.us-east-1.amazonaws.com/presentation-ecr:v1"
          ports:
            - containerPort: 80
