apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
  - name: backend
    port: 8080
    targetPort: backend
  selector:
    app: backend