name: CI of the backend

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        name: Set up JDK 11
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: build with maven
        run: |
          cd ./backend/
          mvn --batch-mode -DskipTests package
          cd ../

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file ./backend/Dockerfile --tag ${{ secrets.AWS_REGISTRY_URL }}/backend

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-2
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.AWS_REGISTRY_URL }}/backend
