name: CI of the frontend

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd ./frontend/
          npm install
          cd ../

      - name: Build for prod
        run: |
          cd ./frontend/
          npm run build:prod
          cd ../

      - name: Build the Docker image
        run: docker build . --file ./frontend/Dockerfile --tag ${{ secrets.AWS_REGISTRY_URL }}/frontend

      - name: Push Docker Image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}
          docker push ${{ secrets.AWS_REGISTRY_URL }}/frontend
